#!/usr/bin/env bash
# Re-vendor lite3 from upstream at a pinned commit and apply local patches.
#
# Usage: scripts/update-vendor.sh [COMMIT]
#   COMMIT defaults to the commit recorded in vendor/lite3/UPSTREAM.
#
# The vendored tree is always the pristine upstream allow-list below plus
# every patch in vendor/patches/ (applied in lexical order). To change
# vendored code, add or edit a patch and re-run this script; never edit
# vendor/lite3/ by hand.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
vendor_dir="$repo_root/vendor/lite3"
patch_dir="$repo_root/vendor/patches"
upstream_url="https://github.com/fastserial/lite3"

commit="${1:-$(sed -n 's/^commit: *//p' "$vendor_dir/UPSTREAM")}"
if [ -z "$commit" ]; then
    echo "error: no commit given and none recorded in $vendor_dir/UPSTREAM" >&2
    exit 1
fi

# Files and directories copied from upstream. Everything else (images,
# Makefile, pkg-config file, upstream README) is left out.
allow_list=(
    LICENSE
    include
    src
    lib
    tests
    examples
)

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

git -C "$work" init -q
git -C "$work" remote add origin "$upstream_url"
git -C "$work" fetch -q --depth 1 origin "$commit"
git -C "$work" checkout -q FETCH_HEAD
full_sha="$(git -C "$work" rev-parse HEAD)"
commit_date="$(git -C "$work" log -1 --format=%cs HEAD)"

rm -rf "$vendor_dir"
mkdir -p "$vendor_dir"
for path in "${allow_list[@]}"; do
    cp -R "$work/$path" "$vendor_dir/$path"
done

shopt -s nullglob
patches=("$patch_dir"/*.patch)
for p in "${patches[@]}"; do
    echo "applying $(basename "$p")"
    git -C "$repo_root" apply --directory=vendor/lite3 --whitespace=nowarn "$p"
done

{
    echo "# Provenance of the vendored lite3 sources. Generated by scripts/update-vendor.sh."
    echo "url: $upstream_url"
    echo "commit: $full_sha"
    echo "date: $commit_date"
    echo "yyjson: $(sed -n 's/^#define YYJSON_VERSION_STRING *"\(.*\)"/\1/p' "$vendor_dir/lib/yyjson/yyjson.h")"
    echo "patches:"
    for p in "${patches[@]}"; do echo "  - $(basename "$p")"; done
} > "$vendor_dir/UPSTREAM"

echo "vendored lite3 $full_sha ($commit_date) with ${#patches[@]} patch(es)"
